### ISSUE TITLE
timeout error on win10 due to use of sigal.SIGALRM

### ISSUE THREAD

**Issue by wildbill9188** [FranGoitia/basketball-reference#7]
\GitHub\basketball_reference>python match_generator.py --league nba --seasons 2003-to-2017
Traceback (most recent call last):
  File "match_generator.py", line 7, in <module>
    from nba import NbaBRefSeason
  File "C:\Users\Bill\Documents\GitHub\basketball_reference\nba.py", line 6, in <module>
    from base import BRefMatch, BRefSeason
  File "C:\Users\Bill\Documents\GitHub\basketball_reference\base.py", line 21, in <module>
    signal.signal(signal.SIGALRM, timeout_handler)
AttributeError: module 'signal' has no attribute 'SIGALRM'

I looked and it seems like I'm not the first person to run into this issue, but perhaps the first to run into it on this specific project.  I found a fix for the same error on a similar project ( https://github.com/Unity-Technologies/ml-agents/pull/9/commits/4958f041a18fb6c55e2827245ff5fc4eaeabfb8c ) but I'm struggling to implement the work-around here.

**Comment by wildbill9188** [comment]
Well, I ended up running it on an Ubuntu VM on my Win10 machine.  I've been running windows via BootCamp on various macs for so long now I guess this must have been obvious for some, but when I first considered it I didnt't think the python-levenshtein package wasn't compatible w linux ... anyways hope this may help someone down the road.  Thank you to the original author for creating this great tool and sharing.

Thanks again,
wildBill
